.TH "Répertoire de référence de petit_robot.X" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de petit_robot.X \- 
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBailleurs\&.c\fP"
.br
.ti -1c
.RI "fichier \fBailleurs\&.h\fP"
.br
.ti -1c
.RI "fichier \fBbitsConfiguration\&.h\fP"
.br
.ti -1c
.RI "fichier \fBcomAsser\&.c\fP"
.br
.ti -1c
.RI "fichier \fBcomAsser\&.h\fP"
.br
.ti -1c
.RI "fichier \fBcomXbee\&.c\fP"
.br
.ti -1c
.RI "fichier \fBcomXbee\&.h\fP"
.br
.ti -1c
.RI "fichier \fBcoordonees\&.c\fP"
.br
.ti -1c
.RI "fichier \fBcoordonees\&.h\fP"
.br
.ti -1c
.RI "fichier \fBdebug\&.c\fP"
.br
.ti -1c
.RI "fichier \fBdebug\&.h\fP"
.br
.RI "\fIContient les fonctions utile pour le débug\&. \fP"
.ti -1c
.RI "fichier \fBdocumentation\&.h\fP"
.br
.ti -1c
.RI "fichier \fBinit\&.c\fP"
.br
.ti -1c
.RI "fichier \fBinit\&.h\fP"
.br
.ti -1c
.RI "fichier \fBmain\&.h\fP"
.br
.RI "\fIContient tout ce qui doit être inclus dans tout le projet\&. \fP"
.ti -1c
.RI "fichier \fBmain_petit_robot\&.c\fP"
.br
.ti -1c
.RI "fichier \fBmouvement\&.c\fP"
.br
.ti -1c
.RI "fichier \fBmouvement\&.h\fP"
.br
.RI "\fIContient les fonctions qui permettent de controler les déplacement du robot\&. \fP"
.ti -1c
.RI "fichier \fBsharp\&.c\fP"
.br
.ti -1c
.RI "fichier \fBsharp\&.h\fP"
.br
.ti -1c
.RI "fichier \fBstrategie\&.c\fP"
.br
.ti -1c
.RI "fichier \fBstrategie\&.h\fP"
.br
.RI "\fIS’occupe de la statégie du robot\&. Les objectifs sont défénis dans un tableau d’objectifs\&. \fP"
.ti -1c
.RI "fichier \fBuart\&.c\fP"
.br
.ti -1c
.RI "fichier \fBuart\&.h\fP"
.br
.ti -1c
.RI "fichier \fBuart_xbee\&.c\fP"
.br
.ti -1c
.RI "fichier \fBuart_xbee\&.h\fP"
.br
.in -1c
