.TH "debug.h" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debug.h \- 
.PP
Contient les fonctions utile pour le débug\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBallumer_del\fP (void)"
.br
.ti -1c
.RI "void \fBeteindre_del\fP (void)"
.br
.ti -1c
.RI "void \fBpause_ms\fP (unsigned short n)"
.br
.ti -1c
.RI "void \fBpause_s\fP (unsigned short n)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Contient les fonctions utile pour le débug\&. 


.PP
\fBA faire\fP
.RS 4
Réécrire allumer_del pour qu¿elle prenne en argument le nom de la del de débug (par exemple une enum) 
.RE
.PP

.PP
Définition dans le fichier \fBdebug\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "void allumer_del (void)"

.PP
Définition à la ligne 7 du fichier debug\&.c\&.
.SS "void eteindre_del (void)"

.PP
Définition à la ligne 12 du fichier debug\&.c\&.
.SS "void pause_ms (unsigned shortn)"

.PP
Définition à la ligne 17 du fichier debug\&.c\&.
.SS "void pause_s (unsigned shortn)"

.PP
Définition à la ligne 27 du fichier debug\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Petit Robot coupe 2014 à partir du code source\&.
