.TH "init.c" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
init.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'sharp\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBinit_osc\fP ()"
.br
.ti -1c
.RI "void \fBio_init\fP (void)"
.br
.ti -1c
.RI "void \fBUART_init_asser\fP ()"
.br
.ti -1c
.RI "void \fBUART_init_xbee\fP ()"
.br
.ti -1c
.RI "void \fBtimer_init\fP ()"
.br
.ti -1c
.RI "void \fBinitTimerEvite\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fB__attribute__\fP ((interrupt, no_auto_psv))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "enum EtatMachine \fBetatSuivant\fP"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void __attribute__ ((interrupt, no_auto_psv))"

.PP
Définition à la ligne 160 du fichier init\&.c\&.
.SS "void init (void)"
Contient le code d’initialisation du pic 
.PP
\fBA faire\fP
.RS 4
migrer le code d’initialisation de cette année ici (s’il y en a) 
.RE
.PP

.PP
Définition à la ligne 146 du fichier init\&.c\&.
.SS "void init_osc ()"

.PP
Définition à la ligne 18 du fichier init\&.c\&.
.SS "void initTimerEvite ()"

.PP
Définition à la ligne 128 du fichier init\&.c\&.
.SS "void io_init (void)"

.PP
Définition à la ligne 33 du fichier init\&.c\&.
.SS "void timer_init ()"

.PP
Définition à la ligne 103 du fichier init\&.c\&.
.SS "void UART_init_asser ()"

.PP
Définition à la ligne 40 du fichier init\&.c\&.
.SS "void UART_init_xbee ()"

.PP
Définition à la ligne 72 du fichier init\&.c\&.
.SH "Documentation des variables"
.PP 
.SS "enum EtatMachine etatSuivant"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Petit Robot coupe 2014 à partir du code source\&.
