.TH "init.h" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
init.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (void)"
.br
.ti -1c
.RI "void \fBQEI_init\fP ()"
.br
.ti -1c
.RI "void \fBtimer_init\fP ()"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void init (void)"
Contient le code d’initialisation du pic 
.PP
\fBA faire\fP
.RS 4
migrer le code d’initialisation de cette année ici (s’il y en a) 
.RE
.PP

.PP
Définition à la ligne 146 du fichier init\&.c\&.
.SS "void QEI_init ()"

.SS "void timer_init ()"

.PP
Définition à la ligne 103 du fichier init\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Petit Robot coupe 2014 à partir du code source\&.
