.TH "T_dividedLong" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T_dividedLong \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "long \fBall\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   short \fBlow\fP"
.br
.ti -1c
.RI "   short \fBhigh\fP"
.br
.ti -1c
.RI "} \fBpart\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 117 du fichier main\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "long all"

.PP
Définition à la ligne 118 du fichier main\&.h\&.
.SS "short high"

.PP
Définition à la ligne 121 du fichier main\&.h\&.
.SS "short low"

.PP
Définition à la ligne 120 du fichier main\&.h\&.
.SS "struct { \&.\&.\&. }   part"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Petit Robot coupe 2014 à partir du code source\&.
