.TH "todo" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Liste des choses à faire 

.IP "\fBGlobal(e) \fBboolean\fP \fP" 1c
fusionner avec Bool  
.IP "\fBGlobal(e) \fBCOORDONNEES_2014_mm\fP \fP" 1c
distances à définir  
.IP "\fBFichier \fBdebug\&.h\fP \fP" 1c
Réécrire allumer_del pour qu¿elle prenne en argument le nom de la del de débug (par exemple une enum)  
.IP "\fBGlobal(e) \fBinit\fP (void)\fP" 1c
migrer le code d’initialisation de cette année ici (s’il y en a)  
.IP "\fBGlobal(e) \fBinit\fP (void)\fP" 1c
migrer le code d’initialisation de cette année ici (s’il y en a)  
.IP "\fBFichier \fBmouvement\&.h\fP \fP" 1c
Les fonctions bouger, avancer et reculer sont trop compliquée et devraient être simplifié  
.IP "\fBGlobal(e) \fBPI\fP \fP" 1c
À déplacer ou il y en a besoin  
.IP "\fBFichier \fBstrategie\&.h\fP \fP" 1c
La stucture objectif devrait être défini dans ce fichier 
.PP

