.TH "TrDefault" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrDefault \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <comXbee\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "unsigned char \fBstub\fP: 4"
.br
.ti -1c
.RI "unsigned char \fBcodet\fP: 4"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 29 du fichier comXbee\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "unsigned char codet"

.PP
Définition à la ligne 32 du fichier comXbee\&.h\&.
.SS "unsigned char stub"

.PP
Définition à la ligne 32 du fichier comXbee\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Petit Robot coupe 2014 à partir du code source\&.
