.TH "TrGenShort" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrGenShort \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <comAsser\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "unsigned short \fBstub\fP:12"
.br
.ti -1c
.RI "unsigned short \fBcodet\fP:4"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 50 du fichier comAsser\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "unsigned short codet"

.PP
Définition à la ligne 53 du fichier comAsser\&.h\&.
.SS "unsigned short stub"

.PP
Définition à la ligne 53 du fichier comAsser\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Petit Robot coupe 2014 à partir du code source\&.
