.TH "TrPos" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrPos \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <comAsser\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "unsigned long \fBy\fP:12"
.br
.ti -1c
.RI "unsigned long \fBx\fP:12"
.br
.ti -1c
.RI "unsigned long \fBstub\fP:4"
.br
.ti -1c
.RI "unsigned long \fBcodet\fP:4"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 86 du fichier comAsser\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "unsigned long codet"

.PP
Définition à la ligne 89 du fichier comAsser\&.h\&.
.SS "unsigned long stub"

.PP
Définition à la ligne 89 du fichier comAsser\&.h\&.
.SS "unsigned long x"

.PP
Définition à la ligne 89 du fichier comAsser\&.h\&.
.SS "unsigned long y"

.PP
Définition à la ligne 89 du fichier comAsser\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Petit Robot coupe 2014 à partir du code source\&.
