.TH "uart_xbee.h" 3 "Jeudi 22 Mai 2014" "Petit Robot coupe 2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uart_xbee.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBsend_xbee_long\fP (long message)"
.br
.ti -1c
.RI "int \fBsend_xbee_short\fP (short message)"
.br
.ti -1c
.RI "int \fBUART_xbee_putc\fP (unsigned char c)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int send_xbee_long (longmessage)"

.PP
Définition à la ligne 49 du fichier uart_xbee\&.c\&.
.SS "int send_xbee_short (shortmessage)"

.PP
Définition à la ligne 57 du fichier uart_xbee\&.c\&.
.SS "int UART_xbee_putc (unsigned charc)"

.PP
Définition à la ligne 24 du fichier uart_xbee\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Petit Robot coupe 2014 à partir du code source\&.
